export const badges = [
    {
        id: 1,
        name: "5 Hundo",
        description: "Complete 500,000 steps",
        image: '../src/assets/badges/badge-500k.png',
        unlockDate: null,
    },
    {
        id: 2,
        name: "Marathon Runner",
        description: "Complete 25,000 steps in a single day",
        image: '../src/assets/badges/badge-500k.png',
        unlockDate: null,
    },
    {
        id: 3,
        name: "Consistent MF",
        description: "Walk at least 8,000 steps for 7 days in a row",
        image: '../src/assets/badges/badge-500k.png',
        unlockDate: null,
    },
    {
        id: 4,
        name: "Weekend Demon",
        description: "Complete 20,000 steps over a weekend",
        image: '../src/assets/badges/badge-500k.png',
        unlockDate: null,
    },
    {
        id: 5,
        name: "One Million",
        description: "Complete 1,000,000 steps",
        image: '../src/assets/badges/badge-500k.png',
        unlockDate: null,
    },
    {
        id: 6,
        name: "Four Seasons",
        description: "Log steps in all four seasons of the year",
        image: '../src/assets/badges/badge-500k.png',
        unlockDate: null,
    },
    {
        id: 7,
        name: "Month Demon",
        description: "Log 300,000 steps in a single month",
        image: '../src/assets/badges/badge-500k.png',
        unlockDate: null,
    },
    {
        id: 8,
        name: "Rain Wizard",
        description: "Log 100,000 total steps on rainy days",
        image: '../src/assets/badges/badge-500k.png',
        unlockDate: null,
    },
    {
        id: 9,
        name: "Rain Demon",
        description: "Complete 10,000 steps in a single rainy day",
        image: '../src/assets/badges/badge-500k.png',
        unlockDate: null,
    },
    {
        id: 10,
        name: "Weekend Wizard",
        description: "Log 500,000 steps on weekends",
        image: '../src/assets/badges/badge-500k.png',
        unlockDate: null,
    },
    {
        id: 11,
        name: "420",
        description: "Blaze it up",
        image: '../src/assets/badges/badge-500k.png',
        unlockDate: null,
    },
    {
        id: 12,
        name: "Lazy Weekend",
        description: "Less than 5,000 steps over a weekend. You must be ill.",
        image: '../src/assets/badges/badge-500k.png',
        unlockDate: null,
    },
    {
        id: 13,
        name: "Summer Solstice",
        description: "Rinsed it on 20th June",
        image: '../src/assets/badges/badge-500k.png',
        unlockDate: null,
    },
];